# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: sherlock@cht.com.tw
description: "Write your site description here. It will be used as your sites meta description as well!"
#baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://yourdomain.com"
twitter_username: 
github_username:  udoblog
facebook_username:  twudo

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
