# Site settings
title: UDO 知識管理
header-img: media/anasayfa.jpg
email: sherlock@cht.com.tw
description: "Design Is Endless Trip"
baseurl: ""
url: "http://udoblog.github.io"
twitter_username: 
github_username:  udoblog
facebook_username:  twudo

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
